### ISSUE TITLE
virtnbdrestore fails with error: "IndexError: list index out of range"

### ISSUE THREAD

**Issue by sor-g** [abbbi/virtnbdbackup#110]
**Version used**
1.9.16

**Describe the bug**
Several VMs backups were created while VMs were off. All backups were succsessful.
When trying to restore (on another machine), for one of the VMs the process failed with error: "IndexError: list index out of range"
Operation was redone three times - backup is successful, but restore for this particular VM fails.

**Expected behavior**
virtnbdrestore should finish  without error

**Hypervisor information:**
 - OS: CentOS 8.3
 - HV type: plain libvirt

**Logfiles:**
virtnbdrestore.log:

[2023-03-01 22:03:39] INFO lib common - printVersion [MainThread]: Version: 1.9.16 Arguments: /usr/bin/virtnbdrestore -cD -i /home/cccc/Downloads/VM-images-BACKs-frm-ZETASM/BACK-test2-for-migration-to-YETA -o /opt/VM-disk-images/restored-from-ZETASM
[2023-03-01 22:03:39] INFO root virtnbdrestore - main [MainThread]: Using latest config file: [/home/cccc/Downloads/VM-images-BACKs-frm-ZETASM/BACK-test2-for-migration-to-YETA/vmconfig.copy.xml]
[2023-03-01 22:03:39] INFO virt client - getDomainDisks [MainThread]: Skipping attached [cdrom] device: [sda].
[2023-03-01 22:03:39] INFO root virtnbdrestore - createDiskFile [MainThread]: Create virtual disk [/opt/VM-disk-images/restored-from-ZETASM/test2.qcow2] format: [qcow2] size: [21474836480] based on: [virtnbdbackup.0]
[2023-03-01 22:03:39] INFO root virtnbdrestore - getQcowConfig [MainThread]: Using QCOW options from backup file: [/home/cccc/Downloads/VM-images-BACKs-frm-ZETASM/BACK-test2-for-migration-to-YETA/sdb.copy.qcow.json]
[2023-03-01 22:03:39] INFO root virtnbdrestore - startNbd [MainThread]: Starting local NBD server on socket: [/var/tmp/virtnbdbackup.139586]
[2023-03-01 22:03:39] INFO nbd client - _printVersion [MainThread]: libnbd version: 1.6.0
[2023-03-01 22:03:39] INFO root virtnbdrestore - startNbd [MainThread]: Started NBD server, PID: [139590]
[2023-03-01 22:03:39] INFO nbd client - connect [MainThread]: Waiting until NBD server at [nbd+unix:///sdb?socket=/var/tmp/virtnbdbackup.139586] is up.
[2023-03-01 22:03:40] INFO nbd client - _getBlockInfo [MainThread]: Using Maximum Block size supported by NBD server: [33554432]
[2023-03-01 22:03:40] INFO nbd client - connect [MainThread]: Connection to NBD backend succeeded.
[2023-03-01 22:03:40] INFO root virtnbdrestore - restoreData [MainThread]: Applying data from backup file [/home/cccc/Downloads/VM-images-BACKs-frm-ZETASM/BACK-test2-for-migration-to-YETA/sdb.copy.data] to target file [/opt/VM-disk-images/restored-from-ZETASM/test2.qcow2].
[2023-03-01 22:04:18] INFO root virtnbdrestore - restoreData [MainThread]: End of stream, [3674341376] bytes of data processed
[2023-03-01 22:04:18] INFO virt client - adjustDomainConfig [MainThread]: Removing uuid setting from vm config.
[2023-03-01 22:04:18] INFO virt client - adjustDomainConfig [MainThread]: Changing name from [test2] to [restore_test2]

command output on terminal:

[root@YETA ~]# virtnbdrestore -cD -i /home/cccc/Downloads/VM-images-BACKs-frm-ZETASM/BACK-test2-for-migration-to-YETA -o /opt/VM-disk-images/restored-from-ZETASM
[2023-03-01 22:03:39] INFO lib common - printVersion [MainThread]: Version: 1.9.16 Arguments: /usr/bin/virtnbdrestore -cD -i /home/cccc/Downloads/VM-images-BACKs-frm-ZETASM/BACK-test2-for-migration-to-YETA -o /opt/VM-disk-images/restored-from-ZETASM
[2023-03-01 22:03:39] INFO root virtnbdrestore - main [MainThread]: Using latest config file: [/home/cccc/Downloads/VM-images-BACKs-frm-ZETASM/BACK-test2-for-migration-to-YETA/vmconfig.copy.xml]
[2023-03-01 22:03:39] INFO virt client - getDomainDisks [MainThread]: Skipping attached [cdrom] device: [sda].
[2023-03-01 22:03:39] INFO root virtnbdrestore - createDiskFile [MainThread]: Create virtual disk [/opt/VM-disk-images/restored-from-ZETASM/test2.qcow2] format: [qcow2] size: [21474836480] based on: [virtnbdbackup.0]
[2023-03-01 22:03:39] INFO root virtnbdrestore - getQcowConfig [MainThread]: Using QCOW options from backup file: [/home/cccc/Downloads/VM-images-BACKs-frm-ZETASM/BACK-test2-for-migration-to-YETA/sdb.copy.qcow.json]
[2023-03-01 22:03:39] INFO root virtnbdrestore - startNbd [MainThread]: Starting local NBD server on socket: [/var/tmp/virtnbdbackup.139586]
[2023-03-01 22:03:39] INFO nbd client - _printVersion [MainThread]: libnbd version: 1.6.0
[2023-03-01 22:03:39] INFO root virtnbdrestore - startNbd [MainThread]: Started NBD server, PID: [139590]
[2023-03-01 22:03:39] INFO nbd client - connect [MainThread]: Waiting until NBD server at [nbd+unix:///sdb?socket=/var/tmp/virtnbdbackup.139586] is up.
[2023-03-01 22:03:40] INFO nbd client - _getBlockInfo [MainThread]: Using Maximum Block size supported by NBD server: [33554432]
[2023-03-01 22:03:40] INFO nbd client - connect [MainThread]: Connection to NBD backend succeeded.
[2023-03-01 22:03:40] INFO root virtnbdrestore - restoreData [MainThread]: Applying data from backup file [/home/cccc/Downloads/VM-images-BACKs-frm-ZETASM/BACK-test2-for-migration-to-YETA/sdb.copy.data] to target file [/opt/VM-disk-images/restored-from-ZETASM/test2.qcow2].
{'checkpointName': 'virtnbdbackup.0',
 'compressed': False,
 'compressionMethod': 'lz4',
 'dataSize': 3674341376,
 'date': '2023-03-01T20:36:45.310806',
 'diskFormat': 'qcow2',
 'diskName': 'sdb',
 'incremental': False,
 'parentCheckpoint': '',
 'streamVersion': 2,
 'virtualSize': 21474836480}
[2023-03-01 22:04:18] INFO root virtnbdrestore - restoreData [MainThread]: End of stream, [3674341376] bytes of data processed
[2023-03-01 22:04:18] INFO virt client - adjustDomainConfig [MainThread]: Removing uuid setting from vm config.
[2023-03-01 22:04:18] INFO virt client - adjustDomainConfig [MainThread]: Changing name from [test2] to [restore_test2]
Traceback (most recent call last):
  File "/usr/bin/virtnbdrestore", line 707, in <module>
    main()
  File "/usr/bin/virtnbdrestore", line 693, in main
    restConfig = restore(args, ConfigFile, virtClient)
  File "/usr/bin/virtnbdrestore", line 475, in restore
    restConfig = virtClient.adjustDomainConfig(args, disk, vmConfig, targetFile)
  File "/usr/lib/python3.6/site-packages/libvirtnbdbackup/virt/client.py", line 317, in adjustDomainConfig
    originalFile = disk.xpath("source")[0].get("file")
IndexError: list index out of range

**Workaround:**

**Comment by abbbi** [comment]
its unable to detect the original disk file to replace the pathes, i need the virtual machine configuratoin file to check where the issue is to reproduce.

**Comment by abbbi** [comment]
i need at least the disk section from the file:

/home/cccc/Downloads/VM-images-BACKs-frm-ZETASM/BACK-test2-for-migration-to-YETA/vmconfig.copy.xml

to analyse. (or the complete file if it doesnt include sensitive data)

**Comment by sor-g** [comment]
Dear Michael,
here is the xml:

<domain type='kvm' xmlns:qemu='http://libvirt.org/schemas/domain/qemu/1.0'>
  <name>test2</name>
  <uuid>6684b6f0-17ab-4f3c-962f-bae17845857d</uuid>
  <title>test2</title>
  <description>test2 - cloned xxxxxxx for testing virtnbdrestore</description>
  <metadata>
    <libosinfo:libosinfo xmlns:libosinfo="http://libosinfo.org/xmlns/libvirt/domain/1.0">
      <libosinfo:os id="http://centos.org/centos/8"/>
    </libosinfo:libosinfo>
  </metadata>
  <memory unit='KiB'>8388608</memory>
  <currentMemory unit='KiB'>8388608</currentMemory>
  <vcpu placement='static'>2</vcpu>
  <os>
    <type arch='x86_64' machine='pc-q35-rhel8.2.0'>hvm</type>
  </os>
  <features>
    <acpi/>
    <apic/>
    <vmport state='off'/>
  </features>
  <cpu mode='host-model' check='partial'/>
  <clock offset='utc'>
    <timer name='rtc' tickpolicy='catchup'/>
    <timer name='pit' tickpolicy='delay'/>
    <timer name='hpet' present='no'/>
  </clock>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>restart</on_reboot>
  <on_crash>destroy</on_crash>
  <pm>
    <suspend-to-mem enabled='no'/>
    <suspend-to-disk enabled='no'/>
  </pm>
  <devices>
    <emulator>/usr/libexec/qemu-kvm</emulator>
    <disk type='file' device='cdrom'>
      <driver name='qemu' type='raw'/>
      <target dev='sda' bus='sata'/>
      <readonly/>
      <address type='drive' controller='0' bus='0' target='0' unit='0'/>
    </disk>
    <disk type='file' device='disk'>
      <driver name='qemu' type='qcow2'/>
      <source file='/opt/VM-images/test2.qcow2'/>
      <target dev='sdb' bus='sata'/>
      <boot order='1'/>
      <address type='drive' controller='0' bus='0' target='0' unit='1'/>
    </disk>
    <controller type='usb' index='0' model='qemu-xhci' ports='15'>
      <address type='pci' domain='0x0000' bus='0x02' slot='0x00' function='0x0'/>
    </controller>
    <controller type='sata' index='0'>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x1f' function='0x2'/>
    </controller>
    <controller type='pci' index='0' model='pcie-root'/>
    <controller type='pci' index='1' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='1' port='0x10'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x0' multifunction='on'/>
    </controller>
    <controller type='pci' index='2' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='2' port='0x11'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x1'/>
    </controller>
    <controller type='pci' index='3' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='3' port='0x12'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x2'/>
    </controller>
    <controller type='pci' index='4' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='4' port='0x13'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x3'/>
    </controller>
    <controller type='pci' index='5' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='5' port='0x14'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x4'/>
    </controller>
    <controller type='pci' index='6' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='6' port='0x15'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x5'/>
    </controller>
    <controller type='virtio-serial' index='0'>
      <address type='pci' domain='0x0000' bus='0x03' slot='0x00' function='0x0'/>
    </controller>
    <interface type='direct'>
      <mac address='52:54:00:51:66:f4'/>
      <source dev='eno1' mode='bridge'/>
      <model type='virtio'/>
      <address type='pci' domain='0x0000' bus='0x01' slot='0x00' function='0x0'/>
    </interface>
    <serial type='pty'>
      <target type='isa-serial' port='0'>
        <model name='isa-serial'/>
      </target>
    </serial>
    <console type='pty'>
      <target type='serial' port='0'/>
    </console>
    <channel type='unix'>
      <target type='virtio' name='org.qemu.guest_agent.0'/>
      <address type='virtio-serial' controller='0' bus='0' port='1'/>
    </channel>
    <channel type='spicevmc'>
      <target type='virtio' name='com.redhat.spice.0'/>
      <address type='virtio-serial' controller='0' bus='0' port='2'/>
    </channel>
    <input type='tablet' bus='usb'>
      <address type='usb' bus='0' port='1'/>
    </input>
    <input type='mouse' bus='ps2'/>
    <input type='keyboard' bus='ps2'/>
    <graphics type='spice' autoport='yes'>
      <listen type='address'/>
      <image compression='off'/>
    </graphics>
    <sound model='ich9'>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x1b' function='0x0'/>
    </sound>
    <audio id='1' type='spice'/>
    <video>
      <model type='qxl' ram='65536' vram='65536' vgamem='16384' heads='1' primary='yes'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x01' function='0x0'/>
    </video>
    <redirdev bus='usb' type='spicevmc'>
      <address type='usb' bus='0' port='2'/>
    </redirdev>
    <redirdev bus='usb' type='spicevmc'>
      <address type='usb' bus='0' port='3'/>
    </redirdev>
    <memballoon model='virtio'>
      <address type='pci' domain='0x0000' bus='0x04' slot='0x00' function='0x0'/>
    </memballoon>
    <rng model='virtio'>
      <backend model='random'>/dev/urandom</backend>
      <address type='pci' domain='0x0000' bus='0x05' slot='0x00' function='0x0'/>
    </rng>
  </devices>
  <qemu:capabilities>
    <qemu:add capability='incremental-backup'/>
  </qemu:capabilities>
</domain>

**Comment by abbbi** [comment]
problem is the ordering of the devices in the VM. The CDROM device (which his removed during adjustment of configuration) is listed in the config before the first real disk device. commit shoult fix this:

https://github.com/abbbi/virtnbdbackup/commit/a6f0e42fc3c37a7a7868aef4dc63d429c2687cd7

can you test?

**Comment by sor-g** [comment]
> problem is the ordering of the devices in the VM. The CDROM device (which his removed during adjustment of configuration) is listed in the config before the first real disk device. This commit should fix this:
> 
> [a6f0e42](https://github.com/abbbi/virtnbdbackup/commit/a6f0e42fc3c37a7a7868aef4dc63d429c2687cd7)
> 
> can you test?
Just tested.
Issue is resolved.
Thanks for quick action!
