### ISSUE TITLE
Issues with transient VM's: TypeError: 'list' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by abbbi** [abbbi/virtnbdbackup#122]
### Discussed in https://github.com/abbbi/virtnbdbackup/discussions/121

<div type='discussions-op-text'>

<sup>Originally posted by **CJBecker** August  1, 2023</sup>
Hi, 

I was seeing that you can set transient vms:
(https://github.com/abbbi/virtnbdbackup#transient-virtual-machines-checkpoint-persistency)

Using this process and setting the checkpoints, the next backup after a VM move appears to attempt to restore checkpoint but fails: 
```
[2023-07-31 20:16:19] INFO root checkpoint - redefine [MainThread]: Loading checkpoint list from: [**********]
[2023-07-31 20:16:19] INFO root checkpoint - redefine [MainThread]: Redefine missing checkpoint: [virtnbdbackup.0]
Traceback (most recent call last):
  File "/usr/bin/virtnbdbackup", line 796, in <module>
    main()
  File "/usr/bin/virtnbdbackup", line 427, in main
    checkpoint.create(args, domObj)
  File "/usr/local/lib/python3.10/dist-packages/virtnbdbackup-1.9.31-py3.10.egg/libvirtnbdbackup/virt/checkpoint.py", line 287, in create
  File "/usr/local/lib/python3.10/dist-packages/virtnbdbackup-1.9.31-py3.10.egg/libvirtnbdbackup/virt/checkpoint.py", line 225, in redefine
  File "/usr/lib/python3/dist-packages/libvirt.py", line 1267, in checkpointCreateXML
    ret = libvirtmod.virDomainCheckpointCreateXML(self._o, xmlDesc, flags)
TypeError: 'list' object cannot be interpreted as an integer
``` 
</div>

**Comment by CJBecker** [comment]
LGTM TY TY

**Comment by abbbi** [comment]
fixed in latest release, thanks
