### ISSUE TITLE
Output folder must not exist (during a remote restore)

### ISSUE THREAD

**Issue by draggeta** [abbbi/virtnbdbackup#152]
**Version used**
Provide output of `virtnbdbackup -V`
1.9.50

**Describe the bug**
Not really a bug, but maybe a documentation update would be handy. In file `virtnbdrestore` line 719 there is the following line:
```python
args.sshClient.sftp.mkdir(args.output)
```
which always tries to create the folder specified with the `-o` parameter (in a remote restore). 

**Expected behavior**
Either just check if the folder exists and do nothing or just update the documentation.

**Hypervisor information:**
 - OS: Ubuntu 22.04
 - HV type: plain libvirt

**Logfiles:**
```python
[2023-12-10 14:40:54] INFO virt client - _connect [MainThread]:  Connected to remote host: [hv01], local host: [backup01]
[2023-12-10 14:40:54] INFO ssh client - connect [MainThread]:  Connecting remote system [hv01] via ssh, username: [root]
[2023-12-10 14:40:54] INFO paramiko.transport transport - _log [Thread-1]:  Connected (version 2.0, client OpenSSH_8.9p1)
[2023-12-10 14:40:54] INFO paramiko.transport transport - _log [Thread-1]:  Authentication (publickey) successful!
[2023-12-10 14:40:54] INFO paramiko.transport.sftp sftp - _log [MainThread]:  [chan 0] Opened sftp connection (server version 3)
Traceback (most recent call last):
  File "/usr/local/bin/virtnbdrestore", line 4, in <module>
    __import__('pkg_resources').run_script('virtnbdbackup==1.9.50', 'virtnbdrestore')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 708, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1528, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.11/dist-packages/virtnbdbackup-1.9.50-py3.11.egg/EGG-INFO/scripts/virtnbdrestore", line 754, in <module>
  File "/usr/local/lib/python3.11/dist-packages/virtnbdbackup-1.9.50-py3.11.egg/EGG-INFO/scripts/virtnbdrestore", line 719, in main
  File "/usr/lib/python3/dist-packages/paramiko/sftp_client.py", line 460, in mkdir
    self._request(CMD_MKDIR, path, attr)
  File "/usr/lib/python3/dist-packages/paramiko/sftp_client.py", line 822, in _request
    return self._read_response(num)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/paramiko/sftp_client.py", line 874, in _read_response
    self._convert_status(msg)
  File "/usr/lib/python3/dist-packages/paramiko/sftp_client.py", line 907, in _convert_status
    raise IOError(text)
OSError: Failure
```

**Workaround:**
Delete the folder.

**Comment by abbbi** [comment]
https://github.com/abbbi/virtnbdbackup/blob/0952034d29be4b59bd162a2dc0b9e09b9cbe2e22/libvirtnbdbackup/common.py#L132

**Comment by abbbi** [comment]
https://github.com/abbbi/virtnbdbackup/blob/0952034d29be4b59bd162a2dc0b9e09b9cbe2e22/libvirtnbdbackup/common.py#L132

Can be used to check if dir Exists 
PR welcome

**Comment by draggeta** [comment]
Nice, I wasn't sure what your preference was so I didn't open a PR. Will work on it :)
