### ISSUE TITLE
new "full" backup / main: operation failed: domain moment virtnbdbackup.1 already exists

### ISSUE THREAD

**Issue by insatomcat** [abbbi/virtnbdbackup#18]
Hello,

I tried to start a new full backup in a new directory and even though the full backup worked, I can't seem to be able to create a incremental one on top of the full one : 

```
$ sudo /home/virtu/virtnbdbackup/virtnbdbackup -d ubuntuCI -l inc -o /mnt/backups/ci_20211004 --compress
[2021-10-05 08:43:00] INFO common - printVersion: Version: 0.25 Arguments: /home/virtu/virtnbdbackup/virtnbdbackup -d ubuntuCI -l inc -o /mnt/backups/ci_20211004 --compress
[2021-10-05 08:43:00] INFO virtnbdbackup - main: Store checkpoints in: /mnt/backups/ci_20211004/checkpoints
[2021-10-05 08:43:00] INFO virtnbdbackup - main: Domain has 1 disks attached which support changed block tracking.
[2021-10-05 08:43:00] INFO virtnbdbackup - main: Attempting to redefine checkpoints from: /mnt/backups/ci_20211004/checkpoints
[2021-10-05 08:43:00] INFO libvirthelper - redefineCheckpoints: Loading checkpoint list from: /mnt/backups/ci_20211004/checkpoints
[2021-10-05 08:43:00] INFO virtnbdbackup - main: Looking for checkpoints
[2021-10-05 08:43:00] INFO virtnbdbackup - main: Found checkpoints, next checkpoint id: 1
[2021-10-05 08:43:00] INFO virtnbdbackup - main: Parent checkpoint name virtnbdbackup.0
[2021-10-05 08:43:00] INFO virtnbdbackup - main: Using checkpoint name: virtnbdbackup.1
[2021-10-05 08:43:00] INFO virtnbdbackup - main: Temporary scratch file target directory: /var/tmp
[2021-10-05 08:43:00] INFO virtnbdbackup - main: Starting backup job.
[2021-10-05 08:43:00] WARNING libvirthelper - fsFreeze: Guest agent is not responding: QEMU guest agent is not connected
[2021-10-05 08:43:00] ERROR virtnbdbackup - main: operation failed: domain moment virtnbdbackup.1 already exists
Traceback (most recent call last):
  File "/home/virtu/virtnbdbackup/virtnbdbackup", line 315, in main
    virtClient.startBackup(
  File "/home/virtu/virtnbdbackup/libvirtnbdbackup/libvirthelper/libvirthelper.py", line 262, in startBackup
    domObj.backupBegin(backupXml, checkpointXml)
  File "/usr/lib/python3/dist-packages/libvirt.py", line 704, in backupBegin
    if ret == -1: raise libvirtError ('virDomainBackupBegin() failed', dom=self)
libvirt.libvirtError: operation failed: domain moment virtnbdbackup.1 already exists
```

The old "bitmaps" seem to be present in the disk image:

```
$ sudo qemu-img info -f qcow2 -U /data/libvirt/images/cibuild/ubuntu20.04.qcow2
image: /data/libvirt/images/cibuild/ubuntu20.04.qcow2
file format: qcow2
virtual size: 300 GiB (322122547200 bytes)
disk size: 178 GiB
cluster_size: 65536
Format specific information:
    compat: 1.1
    lazy refcounts: true
    bitmaps:
        [0]:
            flags:
                [0]: in-use
            name: virtnbdbackup.2
            granularity: 65536
        [1]:
            flags:
                [0]: in-use
            name: virtnbdbackup.1
            granularity: 65536
        [2]:
            flags:
                [0]: in-use
                [1]: auto
            name: virtnbdbackup.3
            granularity: 65536
        [3]:
            flags:
                [0]: in-use
                [1]: auto
            name: virtnbdbackup.0
            granularity: 65536
    refcount bits: 16
    corrupt: false
```

I can't seem to be able to delete it (qemu-img on ubuntu LTS does not have the "bitmap" command).

Can you please advise ?
Thanks a lot.

**Comment by abbbi** [comment]
Was the virtual machine powered off at some point?
Looks like an inconsistency between the bitmap information of the qcow file and the bitmaps that libvirt knows about.
Unfortunately theres no way you can recover that with virtnbdbackup, you need to remove the dangling bitmaps from the qemu image somehow.

**Comment by insatomcat** [comment]
Removing the checkpoints with `virsh checkpoint-delete --checkpointname virtnbdbackup.1 ...` was the way to go
Thanks !
