### ISSUE TITLE
virtnbdrestore errors  if no $HOME Environment variable set

### ISSUE THREAD

**Issue by rodrigo-hissam** [abbbi/virtnbdbackup#197]
I have installed  **virtnbdbackup version 2.11** on Fedora 39, after taking a backup I wanted to verify the backup using the verify command: 

`virtnbdrestore -i /mnt/backups/2024-08-01 -o verify`

There seems to be something wrong, as I am getting the following any time I try to use **virtnbdrestore** 

```
Traceback (most recent call last):
  File "/bin/virtnbdrestore", line 267, in <module>
    main()
  File "/bin/virtnbdrestore", line 166, in main
    argopt.addLogArgs(logopt, parser.prog)
  File "/usr/lib/python3.12/site-packages/libvirtnbdbackup/argopt.py", line 139, in addLogArgs
    default=f"{os.environ['HOME']}/{prog}.log",
               ~~~~~~~~~~^^^^^^^^
  File "<frozen os>", line 685, in __getitem__
KeyError: 'HOME'
```

**Comment by abbbi** [comment]
fixed in latest master branch

**Comment by rodrigo-hissam** [comment]
Thanks @abbbi export the HOME variable made it work.
