### ISSUE TITLE
Error attempting to run incremental backup

### ISSUE THREAD

**Issue by SeeJayEmm** [abbbi/virtnbdbackup#30]
I am using v0.36.  I am running into the following error when trying to run incremental backups. 

````
Traceback (most recent call last):
  File "/usr/local/bin/virtnbdbackup", line 4, in <module>
    __import__('pkg_resources').run_script('virtnbdbackup==0.36', 'virtnbdbackup')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1455, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.9/dist-packages/virtnbdbackup-0.36-py3.9.egg/EGG-INFO/scripts/virtnbdbackup", line 645, in <module>
  File "/usr/local/lib/python3.9/dist-packages/virtnbdbackup-0.36-py3.9.egg/EGG-INFO/scripts/virtnbdbackup", line 300, in main
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
````

This seems to be happening on the 2nd incremental backup.  First one seems to run OK.

I've noticed one commonality.  The <domainname>.cpt file is 0 length on all of the VMs I'm having this issue with.

**Comment by SeeJayEmm** [comment]
So I tested my theory.  Ran a 2nd incremental on one of my VMs and the .cpt file got zeroed out.  I replaced the content of the .cpt (adding the new checkpoint to it so it was accurate) and was able to run a 3rd incremental but it zeroed it out again.

**Comment by SeeJayEmm** [comment]
I'm starting to believe this is an issue on my storage and not a problem with virtnbdbackup. I'm doing some additional testing and will close this issue if that turns out to be the case.

**Comment by SeeJayEmm** [comment]
Ok this is a storage issue on my end. Please disregard.
