### ISSUE TITLE
virtnbdbackup: cannot import name 'CONTEXT_BASE_ALLOCATION' from nbd in Debian Bullseye

### ISSUE THREAD

**Issue by KALRONG** [abbbi/virtnbdbackup#32]
First thanks for the awesome tool!

Im trying to use it on my debian 11 bullseye, installed from the git repository and followed the steps but Im facing the following error when trying to execute it:

`Traceback (most recent call last):
  File "/usr/local/bin/virtnbdbackup", line 4, in <module>
    __import__('pkg_resources').run_script('virtnbdbackup==0.43', 'virtnbdbackup')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1455, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.9/dist-packages/virtnbdbackup-0.43-py3.9.egg/EGG-INFO/scripts/virtnbdbackup", line 31, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.9/dist-packages/virtnbdbackup-0.43-py3.9.egg/libvirtnbdbackup/extenthandler/__init__.py", line 4, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.9/dist-packages/virtnbdbackup-0.43-py3.9.egg/libvirtnbdbackup/extenthandler/extenthandler.py", line 18, in <module>
ImportError: cannot import name 'CONTEXT_BASE_ALLOCATION' from 'nbd' (/usr/local/lib/python3.9/dist-packages/nbd/__init__.py)
`
I have checked the version of the libnbd library in debian and is up to 1.6.1 so this shouldn't be the problem.

Any help will be really appreciated, thanks in advance!

**Comment by abbbi** [comment]
thats strange, im using debian 11 myself and have not yet had that issue.
Are you sure you are using the python3-libnbd binding as provided by debian11?

On my system, its having the CONTEXT_BASE_ALLOCATION setting:

```
abi@cefix ~ $ dpkg -L python3-libnbd | grep nbd.py
/usr/lib/python3/dist-packages/nbd.py
abi@cefix ~ $ grep CONTEXT_BASE_ALLOCATION /usr/lib/python3/dist-packages/nbd.py
CONTEXT_BASE_ALLOCATION = "base:allocation"
    context, for example "CONTEXT_BASE_ALLOCATION".
    context, for example "CONTEXT_BASE_ALLOCATION".
```

**Comment by abbbi** [comment]
see comment -> environment issue.
