### ISSUE TITLE
virtnbdbackup: redefining checkpoints failes

### ISSUE THREAD

**Issue by skleijkers** [abbbi/virtnbdbackup#40]
Hi,

I found a bug in the redefining of checkpoints. I migrated a vm from host a to b and try to make a (diff) backup, now I'm getting the output below. It doesn't matter if I use the --checkpointdir option. When I manually redefine the checkpoint it works (virsh checkpoint-create X --redefine --xmlfile /X/backupset.15/checkpoints/virtnbdbackup.0.xml).

Kind regards,
Stefan

[2022-04-11 20:44:02] INFO common - printVersion [MainThread]: Version: 0.55 Arguments: /usr/bin/virtnbdbackup -d X -l diff -o /X/backupset.15
[2022-04-11 20:44:02] INFO virtnbdbackup - main [MainThread]: Backup level: [diff]
[2022-04-11 20:44:02] INFO virtnbdbackup - main [MainThread]: Domain has 1 disks attached which support changed block tracking.
[2022-04-11 20:44:02] INFO virtnbdbackup - main [MainThread]: Concurrent backup processes: [1]
[2022-04-11 20:44:02] INFO libvirthelper - redefineCheckpoints [MainThread]: Loading checkpoint list from: [X/backupset.15/checkpoints]
[2022-04-11 20:44:02] INFO libvirthelper - redefineCheckpoints [MainThread]: Redefine missing checkpoint: [virtnbdbackup.0]
Traceback (most recent call last):
  File "/usr/bin/virtnbdbackup", line 893, in <module>
    main()
  File "/usr/bin/virtnbdbackup", line 472, in main
    handleCheckpoints(args, virtClient, domObj, lib)
  File "/usr/bin/virtnbdbackup", line 147, in handleCheckpoints
    if virtClient.redefineCheckpoints(domObj, args) is False:
  File "/usr/lib/python3/dist-packages/libvirtnbdbackup/libvirthelper/libvirthelper.py", line 438, in redefineCheckpoints
    domObj.checkpointCreateXML(
  File "/usr/lib/python3/dist-packages/libvirt.py", line 1267, in checkpointCreateXML
    ret = libvirtmod.virDomainCheckpointCreateXML(self._o, xmlDesc, flags)
TypeError: virDomainCheckpointCreateXML() argument 2 must be str or None, not bytes

**Comment by skleijkers** [comment]
Hi,

I think I found the problem. The function needs three arguments and it only gets two.
virDomainCheckpointPtr	virDomainCheckpointCreateXML	(virDomainPtr domain,
							 const char * xmlDesc,
							 unsigned int flags)
and in libvirthelper.py on line 438 it is called with two arguments:
                domObj.checkpointCreateXML(
                    checkpointConfig, libvirt.VIR_DOMAIN_CHECKPOINT_CREATE_REDEFINE
                )

**Comment by skleijkers** [comment]
Works like a charm! Thx.

I only have to test the --checkpointdir option. For a inc and diff backup it isn't necessary, because with those types you are using the directory of the previous full or inc backup and there is also the right checkpoint directory with all the right checkpoints (so the option is not needed and I didn't define it in my test, because I saw in the code it always tries to redefine if there are no checkpoints). But if migrate a machine and you want to make a full backup you need to redefine the previous checkpoints from the previous backup directory, else you get the error the virtnbdbackup.0 checkpoint can't be defined (or deleted, because it doesn't exist), because the bitmap with the virtnbdbackup.0 reference already exists. So for the full you first have to define the old checkpoints, then you can delete them and make a new one.
