### ISSUE TITLE
Dependency Issues Inside of a Virtualenv (nbd)

### ISSUE THREAD

**Issue by GeorgiaM-honestly** [abbbi/virtnbdbackup#44]
Hello, I am attempting to get your wonderful looking project working inside of a virtualenv. In the end I have issues with nbd (I think) and obtain some errors that I don't understand...

- Install as root inside of a virtualenv

```
mkdir ~/virtualenvs 1> /dev/null 2> /dev/null ; cd ~/virtualenvs && git clone https://github.com/abbbi/virtnbdbackup.git && virtualenv -p $(which python3) virtnbdbackup && source virtnbdbackup/bin/activate &&  cd ~/virtualenvs/virtnbdbackup && python3 setup.py install
```

- Exit the shell, open a new shell, then activate

```
cd ~/virtualenvs/virtnbdbackup && source bin/activate
```

- Try to run

```
# cd /var/lib/libvirt/images && mkdir backups-test && virtnbdbackup -d Seeborgs_-_01-10 -l full -o /var/lib/libvirt/images/backups-test

Traceback (most recent call last):
  File "/root/virtualenvs/virtnbdbackup/bin/virtnbdbackup", line 4, in <module>
    __import__('pkg_resources').run_script('virtnbdbackup==0.61', 'virtnbdbackup')
  File "/root/virtualenvs/virtnbdbackup/lib/python3.9/site-packages/pkg_resources/__init__.py", line 672, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/root/virtualenvs/virtnbdbackup/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1479, in run_script
    exec(script_code, namespace, namespace)
  File "/root/virtualenvs/virtnbdbackup/lib/python3.9/site-packages/virtnbdbackup-0.61-py3.9.egg/EGG-INFO/scripts/virtnbdbackup", line 32, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/root/virtualenvs/virtnbdbackup/lib/python3.9/site-packages/virtnbdbackup-0.61-py3.9.egg/libvirtnbdbackup/common/__init__.py", line 21, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/root/virtualenvs/virtnbdbackup/lib/python3.9/site-packages/virtnbdbackup-0.61-py3.9.egg/libvirtnbdbackup/common/common.py", line 12, in <module>
ModuleNotFoundError: No module named 'lz4'
```

- ... Didn't the requirements get installed?

```
# python -m pip install -r ~/virtualenvs/virtnbdbackup/requirements.txt

Collecting libvirt-python>=6.0.0
  Using cached libvirt_python-8.4.0-cp39-cp39-linux_x86_64.whl
Collecting tqdm
  Using cached tqdm-4.64.0-py2.py3-none-any.whl (78 kB)
Collecting lz4>=2.1.2
  Using cached lz4-4.0.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.2 MB)
Installing collected packages: libvirt-python, tqdm, lz4
Successfully installed libvirt-python-8.4.0 lz4-4.0.1 tqdm-4.64.0
```

- No nbd?

```
# virtnbdbackup -d Seeborgs_-_01-10 -l full -o /var/lib/libvirt/images/backups-test

Traceback (most recent call last):
  File "/root/virtualenvs/virtnbdbackup/bin/virtnbdbackup", line 4, in <module>
    __import__('pkg_resources').run_script('virtnbdbackup==0.61', 'virtnbdbackup')
  File "/root/virtualenvs/virtnbdbackup/lib/python3.9/site-packages/pkg_resources/__init__.py", line 672, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/root/virtualenvs/virtnbdbackup/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1479, in run_script
    exec(script_code, namespace, namespace)
  File "/root/virtualenvs/virtnbdbackup/lib/python3.9/site-packages/virtnbdbackup-0.61-py3.9.egg/EGG-INFO/scripts/virtnbdbackup", line 33, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/root/virtualenvs/virtnbdbackup/lib/python3.9/site-packages/virtnbdbackup-0.61-py3.9.egg/libvirtnbdbackup/nbdhelper/__init__.py", line 21, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/root/virtualenvs/virtnbdbackup/lib/python3.9/site-packages/virtnbdbackup-0.61-py3.9.egg/libvirtnbdbackup/nbdhelper/nbdhelper.py", line 20, in <module>
ModuleNotFoundError: No module named 'nbd'
```

```
# python -m pip install nbd
Collecting nbd
  Using cached nbd-0.2-py3-none-any.whl
Collecting nbconvert
  Using cached nbconvert-6.5.0-py3-none-any.whl (561 kB)
Collecting ipython
  Using cached ipython-8.4.0-py3-none-any.whl (750 kB)
Collecting nbformat
  Using cached nbformat-5.4.0-py3-none-any.whl (73 kB)
Collecting jedi>=0.16
  Using cached jedi-0.18.1-py2.py3-none-any.whl (1.6 MB)
Collecting pickleshare
  Using cached pickleshare-0.7.5-py2.py3-none-any.whl (6.9 kB)
Collecting matplotlib-inline
  Using cached matplotlib_inline-0.1.3-py3-none-any.whl (8.2 kB)
Collecting backcall
  Using cached backcall-0.2.0-py2.py3-none-any.whl (11 kB)
Collecting prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0
  Using cached prompt_toolkit-3.0.29-py3-none-any.whl (381 kB)
Collecting pygments>=2.4.0
  Using cached Pygments-2.12.0-py3-none-any.whl (1.1 MB)
Collecting traitlets>=5
  Using cached traitlets-5.3.0-py3-none-any.whl (106 kB)
Requirement already satisfied: setuptools>=18.5 in /root/virtualenvs/virtnbdbackup/lib/python3.9/site-packages (from ipython->nbd) (62.1.0)
Collecting stack-data
  Using cached stack_data-0.3.0-py3-none-any.whl (23 kB)
Collecting decorator
  Using cached decorator-5.1.1-py3-none-any.whl (9.1 kB)
Collecting pexpect>4.3
  Using cached pexpect-4.8.0-py2.py3-none-any.whl (59 kB)
Collecting tinycss2
  Using cached tinycss2-1.1.1-py3-none-any.whl (21 kB)
Collecting packaging
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting MarkupSafe>=2.0
  Using cached MarkupSafe-2.1.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Collecting bleach
  Using cached bleach-5.0.0-py3-none-any.whl (160 kB)
Collecting pandocfilters>=1.4.1
  Using cached pandocfilters-1.5.0-py2.py3-none-any.whl (8.7 kB)
Collecting nbclient>=0.5.0
  Using cached nbclient-0.6.4-py3-none-any.whl (71 kB)
Collecting jinja2>=3.0
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting jupyterlab-pygments
  Using cached jupyterlab_pygments-0.2.2-py2.py3-none-any.whl (21 kB)
Collecting entrypoints>=0.2.2
  Using cached entrypoints-0.4-py3-none-any.whl (5.3 kB)
Collecting beautifulsoup4
  Using cached beautifulsoup4-4.11.1-py3-none-any.whl (128 kB)
Collecting jupyter-core>=4.7
  Using cached jupyter_core-4.10.0-py3-none-any.whl (87 kB)
Collecting defusedxml
  Using cached defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)
Collecting mistune<2,>=0.8.1
  Using cached mistune-0.8.4-py2.py3-none-any.whl (16 kB)
Collecting fastjsonschema
  Using cached fastjsonschema-2.15.3-py3-none-any.whl (22 kB)
Collecting jsonschema>=2.6
  Using cached jsonschema-4.6.0-py3-none-any.whl (80 kB)
Collecting parso<0.9.0,>=0.8.0
  Using cached parso-0.8.3-py2.py3-none-any.whl (100 kB)
Collecting pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0
  Using cached pyrsistent-0.18.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (115 kB)
Collecting attrs>=17.4.0
  Using cached attrs-21.4.0-py2.py3-none-any.whl (60 kB)
Collecting jupyter-client>=6.1.5
  Using cached jupyter_client-7.3.4-py3-none-any.whl (132 kB)
Collecting nest-asyncio
  Using cached nest_asyncio-1.5.5-py3-none-any.whl (5.2 kB)
Collecting ptyprocess>=0.5
  Using cached ptyprocess-0.7.0-py2.py3-none-any.whl (13 kB)
Collecting wcwidth
  Using cached wcwidth-0.2.5-py2.py3-none-any.whl (30 kB)
Collecting soupsieve>1.2
  Using cached soupsieve-2.3.2.post1-py3-none-any.whl (37 kB)
Collecting webencodings
  Using cached webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Collecting six>=1.9.0
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting pyparsing!=3.0.5,>=2.0.2
  Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
Collecting asttokens
  Using cached asttokens-2.0.5-py2.py3-none-any.whl (20 kB)
Collecting pure-eval
  Using cached pure_eval-0.2.2-py3-none-any.whl (11 kB)
Collecting executing
  Using cached executing-0.8.3-py2.py3-none-any.whl (16 kB)
Collecting pyzmq>=23.0
  Using cached pyzmq-23.2.0-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.1 MB)
Collecting tornado>=6.0
  Using cached tornado-6.1-cp39-cp39-manylinux2010_x86_64.whl (427 kB)
Collecting python-dateutil>=2.8.2
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Installing collected packages: webencodings, wcwidth, pure-eval, ptyprocess, pickleshare, mistune, fastjsonschema, executing, backcall, traitlets, tornado, tinycss2, soupsieve, six, pyzmq, pyrsistent, pyparsing, pygments, prompt-toolkit, pexpect, parso, pandocfilters, nest-asyncio, MarkupSafe, jupyterlab-pygments, entrypoints, defusedxml, decorator, attrs, python-dateutil, packaging, matplotlib-inline, jupyter-core, jsonschema, jinja2, jedi, bleach, beautifulsoup4, asttokens, stack-data, nbformat, jupyter-client, nbclient, ipython, nbconvert, nbd
Successfully installed MarkupSafe-2.1.1 asttokens-2.0.5 attrs-21.4.0 backcall-0.2.0 beautifulsoup4-4.11.1 bleach-5.0.0 decorator-5.1.1 defusedxml-0.7.1 entrypoints-0.4 executing-0.8.3 fastjsonschema-2.15.3 ipython-8.4.0 jedi-0.18.1 jinja2-3.1.2 jsonschema-4.6.0 jupyter-client-7.3.4 jupyter-core-4.10.0 jupyterlab-pygments-0.2.2 matplotlib-inline-0.1.3 mistune-0.8.4 nbclient-0.6.4 nbconvert-6.5.0 nbd-0.2 nbformat-5.4.0 nest-asyncio-1.5.5 packaging-21.3 pandocfilters-1.5.0 parso-0.8.3 pexpect-4.8.0 pickleshare-0.7.5 prompt-toolkit-3.0.29 ptyprocess-0.7.0 pure-eval-0.2.2 pygments-2.12.0 pyparsing-3.0.9 pyrsistent-0.18.1 python-dateutil-2.8.2 pyzmq-23.2.0 six-1.16.0 soupsieve-2.3.2.post1 stack-data-0.3.0 tinycss2-1.1.1 tornado-6.1 traitlets-5.3.0 wcwidth-0.2.5 webencodings-0.5.1
```

```
# virtnbdbackup -d Seeborgs_-_01-10 -l full -o /var/lib/libvirt/images/backups-test

Traceback (most recent call last):
  File "/root/virtualenvs/virtnbdbackup/bin/virtnbdbackup", line 4, in <module>
    __import__('pkg_resources').run_script('virtnbdbackup==0.61', 'virtnbdbackup')
  File "/root/virtualenvs/virtnbdbackup/lib/python3.9/site-packages/pkg_resources/__init__.py", line 672, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/root/virtualenvs/virtnbdbackup/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1479, in run_script
    exec(script_code, namespace, namespace)
  File "/root/virtualenvs/virtnbdbackup/lib/python3.9/site-packages/virtnbdbackup-0.61-py3.9.egg/EGG-INFO/scripts/virtnbdbackup", line 34, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/root/virtualenvs/virtnbdbackup/lib/python3.9/site-packages/virtnbdbackup-0.61-py3.9.egg/libvirtnbdbackup/extenthandler/__init__.py", line 21, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/root/virtualenvs/virtnbdbackup/lib/python3.9/site-packages/virtnbdbackup-0.61-py3.9.egg/libvirtnbdbackup/extenthandler/extenthandler.py", line 18, in <module>
ImportError: cannot import name 'CONTEXT_BASE_ALLOCATION' from 'nbd' (/root/virtualenvs/virtnbdbackup/lib/python3.9/site-packages/nbd/__init__.py)
```

At this point, I do not understand what to try next. Thank you for taking the time to read!

**Comment by abbbi** [comment]
the pip3 nbd module is not the one you need, thus you get the CONTEXT_BASE_ALLOCATINO Error. You need the libnbd bindings from the libnbd project within the virtualenv: https://github.com/libguestfs/libnbd

libnbd is a C based library with python bindings, it is not the one shipped with pip

**Comment by GeorgiaM-honestly** [comment]
Okay, thanks for the feedback and clarification. I was able to get that accomplished. This is what I used for the initial setup inside of a new virtualenv. Once activated, the tool works, though it says that the domain does not have incremental backups enabled, and I have not been able to get past that. What I found regarding editing the domains .xml gets rejected by virsh edit for not matching the xml schema, and the xml editor in virt-manager silently deletes it. That is outside the scope of this issue however I wanted to mention it.


mkdir ~/virtualenvs 1> /dev/null 2> /dev/null ; cd ~/virtualenvs && git clone https://github.com/abbbi/virtnbdbackup.git && virtualenv -p $(which python3) virtnbdbackup && source virtnbdbackup/bin/activate &&  cd ~/virtualenvs/virtnbdbackup && wget -U blah https://download.libguestfs.org/libnbd/1.12-stable/libnbd-1.12.4.tar.gz && tar xzf libnbd-1.12.4.tar.gz && python -m pip install ocaml && cd libnbd-1.12.4 && ./configure --prefix=/root/virtualenvs/virtnbdbackup/ --exec-prefix=/root/virtualenvs/virtnbdbackup/ && make && make check && make install && cd .. && python -m pip install -r requirements.txt && python setup.py install

**Comment by abbbi** [comment]
> What I found regarding editing the domains .xml gets rejected by virsh edit for not matching the xml schema, and the xml editor in virt-manager silently deletes it. That is outside the scope of this issue however I wanted to mention it.

which libvirt version used? newer versions might not need to specifically enable the incremental backup setting anymore,
see #4

**Comment by abbbi** [comment]
Note also that you may need to specifically change the first line in the XML too, it must include the special
schema version:

`<domain type='kvm' id='1' xmlns:qemu='http://libvirt.org/schemas/domain/qemu/1.0'>`

**Comment by GeorgiaM-honestly** [comment]
Thanks for the information. As discussed on IRC, I tried that with virsh edit however it silently drops the edit. I'm using libvirt 8.2.0 which may already have the incremental backup capability on by default.

As directed I commented out line 454 from the current master virtnbdbackup ( https://github.com/abbbi/virtnbdbackup/blob/master/virtnbdbackup#L454 ) and a session did complete. Here is the requested output:

```
[2022-06-21 08:44:29] INFO common - printVersion [MainThread]: Version: 0.61 Arguments: /root/virtualenvs/virtnbdbackup/bin/virtnbdbackup -d Seeborgs_-_01-10 -l full -o /var/lib/libvirt/images/backups-test
[2022-06-21 08:44:29] INFO virtnbdbackup - main [MainThread]: Backup level: [full]
[2022-06-21 08:44:29] INFO virtnbdbackup - main [MainThread]: Libvirt library version: 8002000
[2022-06-21 08:44:29] ERROR virtnbdbackup - main [MainThread]: Domain is missing required incremental-backup capability.
[2022-06-21 08:44:29] WARNING virtnbdbackup - setOfflineArguments [MainThread]: Domain is offline, resetting backup options
[2022-06-21 08:44:29] INFO virtnbdbackup - setOfflineArguments [MainThread]: Backup level: [copy]
[2022-06-21 08:44:29] INFO libvirthelper - getDomainDisks [MainThread]: Skipping attached CDROM / Floppy: [sda]
[2022-06-21 08:44:29] INFO virtnbdbackup - main [MainThread]: Domain has 1 disks attached which support changed block tracking.
[2022-06-21 08:44:29] INFO virtnbdbackup - main [MainThread]: Concurrent backup processes: [1]
[2022-06-21 08:44:29] INFO virtnbdbackup - handleCheckpoints [MainThread]: Checkpoint handling
[2022-06-21 08:44:29] INFO virtnbdbackup - main [MainThread]: Temporary scratch file target directory: /var/tmp
[2022-06-21 08:44:29] INFO virtnbdbackup - main [MainThread]: NDB Endpoint socket: /var/tmp/virtnbdbackup.19951
[2022-06-21 08:44:29] INFO virtnbdbackup - backupDisk [vda]: Offline backup, starting NDB Service
[2022-06-21 08:44:29] INFO virtnbdbackup - backupDisk [vda]: NDB Service started
[2022-06-21 08:44:29] INFO nbdhelper - version [vda]: libnbd version: 1.12.4
[2022-06-21 08:44:29] INFO nbdhelper - waitForServer [vda]: Waiting until NBD server on socket [/var/tmp/virtnbdbackup.19951.vda] is up.
[2022-06-21 08:44:30] INFO nbdhelper - getBlockInfo [vda]: Using Maximum Block size supported by NBD server: [33554432]
[2022-06-21 08:44:30] INFO nbdhelper - waitForServer [vda]: Connection to NBD backend succeeded.
[2022-06-21 08:44:30] INFO virtnbdbackup - backupDisk [vda]: Got 1052 extents to backup.
[2022-06-21 08:44:30] INFO virtnbdbackup - backupDisk [vda]: 26843545600 bytes disk size
[2022-06-21 08:44:30] INFO virtnbdbackup - backupDisk [vda]: 20174798848 bytes of data extents to backup
[2022-06-21 08:44:30] INFO virtnbdbackup - getWriter [vda]: Write data to target file: /var/lib/libvirt/images/backups-test/vda.copy.data.partial
[2022-06-21 08:44:30] INFO virtnbdbackup - backupDisk [vda]: Creating thin provisioned stream backup image
[2022-06-21 08:45:40] INFO virtnbdbackup - backupDisk [vda]: Stopping NBD Service                                                                                                                        
[2022-06-21 08:45:40] INFO virtnbdbackup - backupConfig [MainThread]: Saving VM config to: [/var/lib/libvirt/images/backups-test/vmconfig.virtnbdbackup.0.xml]
[2022-06-21 08:45:40] INFO virtnbdbackup - main [MainThread]: Finished successfully
```

**Comment by abbbi** [comment]
thanks, can you try with changes from branch:

https://github.com/abbbi/virtnbdbackup/tree/incheck

should work for you.

**Comment by GeorgiaM-honestly** [comment]
Works great!

```
[2022-06-21 09:24:39] INFO common - printVersion [MainThread]: Version: 0.61 Arguments: /root/virtualenvs/virtnbdbackup/bin/virtnbdbackup -d Seeborgs_-_01-10 -l full -o /var/lib/libvirt/images/backups-test
[2022-06-21 09:24:39] INFO virtnbdbackup - main [MainThread]: Backup level: [full]
[2022-06-21 09:24:39] INFO virtnbdbackup - main [MainThread]: Libvirt library version: 8002000
[2022-06-21 09:24:39] WARNING virtnbdbackup - setOfflineArguments [MainThread]: Domain is offline, resetting backup options
[2022-06-21 09:24:39] INFO virtnbdbackup - setOfflineArguments [MainThread]: Backup level: [copy]
[2022-06-21 09:24:39] INFO libvirthelper - getDomainDisks [MainThread]: Skipping attached CDROM / Floppy: [sda]
[2022-06-21 09:24:39] INFO virtnbdbackup - main [MainThread]: Domain has 1 disks attached which support changed block tracking.
[2022-06-21 09:24:39] INFO virtnbdbackup - main [MainThread]: Concurrent backup processes: [1]
[2022-06-21 09:24:39] INFO virtnbdbackup - handleCheckpoints [MainThread]: Checkpoint handling
[2022-06-21 09:24:39] INFO virtnbdbackup - main [MainThread]: Temporary scratch file target directory: /var/tmp
[2022-06-21 09:24:39] INFO virtnbdbackup - main [MainThread]: NDB Endpoint socket: /var/tmp/virtnbdbackup.11589
[2022-06-21 09:24:39] INFO virtnbdbackup - backupDisk [vda]: Offline backup, starting NDB Service
[2022-06-21 09:24:39] INFO virtnbdbackup - backupDisk [vda]: NDB Service started
[2022-06-21 09:24:39] INFO nbdhelper - version [vda]: libnbd version: 1.12.4
[2022-06-21 09:24:39] INFO nbdhelper - waitForServer [vda]: Waiting until NBD server on socket [/var/tmp/virtnbdbackup.11589.vda] is up.
[2022-06-21 09:24:40] INFO nbdhelper - getBlockInfo [vda]: Using Maximum Block size supported by NBD server: [33554432]
[2022-06-21 09:24:40] INFO nbdhelper - waitForServer [vda]: Connection to NBD backend succeeded.
[2022-06-21 09:24:40] INFO virtnbdbackup - backupDisk [vda]: Got 1052 extents to backup.
[2022-06-21 09:24:40] INFO virtnbdbackup - backupDisk [vda]: 26843545600 bytes disk size
[2022-06-21 09:24:40] INFO virtnbdbackup - backupDisk [vda]: 20174798848 bytes of data extents to backup
[2022-06-21 09:24:40] INFO virtnbdbackup - getWriter [vda]: Write data to target file: /var/lib/libvirt/images/backups-test/vda.copy.data.partial
[2022-06-21 09:24:40] INFO virtnbdbackup - backupDisk [vda]: Creating thin provisioned stream backup image
[2022-06-21 09:25:16] INFO virtnbdbackup - backupDisk [vda]: Stopping NBD Service                                                                                                                        
[2022-06-21 09:25:16] INFO virtnbdbackup - backupConfig [MainThread]: Saving VM config to: [/var/lib/libvirt/images/backups-test/vmconfig.virtnbdbackup.0.xml]
[2022-06-21 09:25:16] INFO virtnbdbackup - main [MainThread]: Finished successfully
```

**Comment by abbbi** [comment]
thanks, merged to master.
