### ISSUE TITLE
Remote backup fails to copy [loader] file

### ISSUE THREAD

**Issue by aze827** [abbbi/virtnbdbackup#74]
**Version used**
1.8.1

**Describe the bug**
When running a remote backup, after saving VM config xml, the job ends with the following error while copying boot config [loader].

**Expected behavior**
File should be copying correctly.

**Hypervisor information:**
 - OS: Rocky Linux release 8.6 (Green Obsidian)
 - HV: libvirtd (libvirt) 8.0.0

**Logfiles:**
[2022-10-25 17:48:45] INFO virtnbdbackup - backupConfig [MainThread]: Saving VM config to: [/tmp/rocky8.5//vmconfig.virtnbdbackup.0.xml]
[2022-10-25 17:48:45] INFO sshutil - connect [MainThread]: Connecting remote system via ssh, username: [root]
[2022-10-25 17:48:45] INFO transport - _log [Thread-2]: Connected (version 2.0, client OpenSSH_8.0)
[2022-10-25 17:48:45] INFO transport - _log [Thread-2]: Authentication (publickey) successful!
[2022-10-25 17:48:45] INFO virtnbdbackup - backupBootConfig [MainThread]: Save additional boot config [loader] to: [/tmp/rocky8.5//OVMF_CODE.secboot.fd.virtnbdbackup.0]
Traceback (most recent call last):
  File "/usr/bin/virtnbdbackup", line 983, in <module>
    main()
  File "/usr/bin/virtnbdbackup", line 620, in main
    backupBootConfig(args, virtClient)
  File "/usr/bin/virtnbdbackup", line 709, in backupBootConfig
    lib.copy(val, tFile, remoteCopy)
  File "/usr/lib/python3.6/site-packages/libvirtnbdbackup/common/common.py", line 155, in copy
    sshClient.copy(source, target)
AttributeError: 'function' object has no attribute 'copy'

**Comment by abbbi** [comment]
hi,

can reproduce, can you check with dev branch / the following fix:

https://github.com/abbbi/virtnbdbackup/commit/310b6861adab2f6eb131a216eac8df558e4c3184

**Comment by aze827** [comment]
Hi again,

After using dev branch, it now works as intended.

Thanks a lot

```
[2022-10-25 18:51:22] INFO nbdhelper - waitForServer [vda]: Connection to NBD backend succeeded.
[2022-10-25 18:51:22] INFO virtnbdbackup - backupDisk [vda]: Got 64 extents to backup.
[2022-10-25 18:51:22] INFO virtnbdbackup - backupDisk [vda]: 21474836480 bytes disk size
[2022-10-25 18:51:22] INFO virtnbdbackup - backupDisk [vda]: 21460221952 bytes of data extents to backup
[2022-10-25 18:51:22] INFO virtnbdbackup - getWriter [vda]: Write data to target file: [/tmp/rocky8.5//vda.full.data.partial].
[2022-10-25 18:51:22] INFO virtnbdbackup - backupDisk [vda]: Creating thin provisioned stream backup image
[2022-10-25 18:54:28] INFO virtnbdbackup - main [MainThread]: Backup jobs finished, stopping backup task.
[2022-10-25 18:54:28] INFO virtnbdbackup - backupConfig [MainThread]: Saving VM config to: [/tmp/rocky8.5//vmconfig.virtnbdbackup.0.xml]
[2022-10-25 18:54:28] INFO sshutil - connect [MainThread]: Connecting remote system via ssh, username: [root]
[2022-10-25 18:54:28] INFO transport - _log [Thread-2]: Connected (version 2.0, client OpenSSH_8.0)
[2022-10-25 18:54:29] INFO transport - _log [Thread-2]: Authentication (publickey) successful!
[2022-10-25 18:54:29] INFO virtnbdbackup - backupBootConfig [MainThread]: Save additional boot config [loader] to: [/tmp/rocky8.5//OVMF_CODE.secboot.fd.virtnbdbackup.0]
[2022-10-25 18:54:29] INFO sshutil - copyFrom [MainThread]: Downloading file [/usr/share/edk2/ovmf/OVMF_CODE.secboot.fd] to [/tmp/rocky8.5//OVMF_CODE.secboot.fd.virtnbdbackup.0]
[2022-10-25 18:54:29] INFO sftp - _log [MainThread]: [chan 0] Opened sftp connection (server version 3)
[2022-10-25 18:54:29] INFO virtnbdbackup - backupBootConfig [MainThread]: Save additional boot config [nvram] to: [/tmp/rocky8.5//rocky8.5_VARS.fd.virtnbdbackup.0]
[2022-10-25 18:54:29] INFO sshutil - copyFrom [MainThread]: Downloading file [/var/lib/libvirt/qemu/nvram/rocky8.5_VARS.fd] to [/tmp/rocky8.5//rocky8.5_VARS.fd.virtnbdbackup.0]
[2022-10-25 18:54:29] INFO sftp - _log [MainThread]: [chan 1] Opened sftp connection (server version 3)
[2022-10-25 18:54:29] INFO sftp - _log [MainThread]: [chan 2] Opened sftp connection (server version 3)
[2022-10-25 18:54:29] INFO sftp - _log [MainThread]: [chan 3] Opened sftp connection (server version 3)
[2022-10-25 18:54:29] INFO sftp - _log [MainThread]: [chan 3] sftp session closed.
[2022-10-25 18:54:29] INFO virtnbdbackup - main [MainThread]: Finished successfully
```
